#!/bin/bash

# run-tests and publish jars
# sbt test publish
sbt doc
# checkout repo again but with gh-pages branch
mkdir -p target
rm -rf target/site
mkdir -p target/site
git clone git@github.com:backchatio/hookup.git target/site
cd target/site
git checkout gh-pages
git rm -rf *
touch .nojekyll
cat > .gitignore <<DOC
_site
.idea*
project
src
target
work
_cache
DOC
echo "1.9.3-p125"
# generate site 
cd ../../src/main/site
jekyll
# generate jsdoc 
cd ../node
npm install
npm test 
node_modules/jsdoc-toolkit/app/run.js -d=../../../target/site/jsdoc -t=node_modules/jsdoc-toolkit/templates/codeview lib
# # generate yardocs 
# # first write the yardocs
# # generate scaladoc 
cd ../../..
mv target/scala-2.9.1/api target/site/scaladoc
cp -R target/jekyll/* target/site/
# commit changes to gh-pages
cd target/site
git add .
git commit -a -m 'new release'
git push
cd ../..

